### ISSUE TITLE
Cursor jumps to the beginning of the text when two keys are pressed

### ISSUE THREAD

**Issue by wobini-fun** [RIP21/react-simplemde-editor#209] opened 2022-10-10 18:13 UTC
Versions used:
"react": "^18.2.0"
"easymde": "2.18.0"
"react-simplemde-editor" "5.2.0" 

Used browser:
 Brave

Hi there, i am facing a strange issue:
If i use the controlled component with the value assigned and a onChange listener (as shown in the [README](https://github.com/RIP21/react-simplemde-editor#controlled-usage) file) the cursor jumps from time to time at the beginning of the text. This seems to happen only when i press two keys at the same time.

Thanks in advance

**Comment by RIP21** [comment] 2022-10-10 19:39
Do you have a StrictMode wrapping it?
Please make reproduction and record a video of it. Use Loom or whatever you prefer.
Thanks.

**Comment by wobini-fun** [comment] 2022-10-11 18:10
Thank you for the fast reply. I created a minimal [sample repository](https://github.com/wobini-fun/easy-mde-test) . 
And here is a short video of the result:

[cursor jumping.webm](https://user-images.githubusercontent.com/53572828/195170996-9344be99-8944-4f55-b66a-0fa92c4e87f4.webm)

Additionally on this setup i have the problem that the preview is undefined see next screencast. The value seems not to be set.

[preview not working.webm](https://user-images.githubusercontent.com/53572828/195171074-79c192eb-2cf5-4783-8335-2ee36253fa08.webm)

**Comment by RIP21** [comment] 2022-10-12 14:41
You should use a newer version of the easymde 2.18.0 to fix the broken preview. It's a bug on their side. 
Regarding the cursor going back, I cannot reproduce that in the demo I have hosted, so it may probably be related to older version of easymde or it being in the dev mode meaning it is a bit slower. In production, it won't be a thing probably.

Also, make sure you memoize your `onChange` handler like that.

```tsx
export const ControlledUsage = () => {
  const [value, setValue] = useState("Initial value");

  const onChange = useCallback((value: string) => {
    setValue(value);
  }, []);

  return <SimpleMdeReact value={value} onChange={onChange} />;
};
```
You're not doing that and it may be causing these issues too.

Closing for now as it's not much actionable. If it's still broken even if it's built for production. then feel free to reopen. Also, I recommend you to host reproductions on codesanbox or similar as it's MUCH easier to check than doing `git clone` and whatnot.

**Closed** 2022-10-12 14:41 UTC
